language: node_js
node_js:
  - "0.11"
  - "0.10"

before_script:
  - gem install jekyll

script:
  - npm test
  - cd docs/ && jekyll build

notifications:
  webhooks:
    urls:
      - secure: "cMEAngs4eTdn3DUNyHFaQyEEKFjFssgKjYmHYEl1Ufson5lfIARQb2ZelRcec4KA8XKck1ATZKoKrdXfttBVfudM7cRrJwM8TZ3C8CSDjFbEYcfkFnIVbfnh0iqBBZ+FTyfyKca7+QbHoleoANpIpdlrM9tFqIIHAHPAUlUO5kw="

    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
