import a
import foo as c

humbug = {a: 1, b: 2, c: 3}
a = [true, false, null, 1, 2, 3, a, b]
b = (1*(66-6)*2+1>>3)==5
b *= 2
c /= 6

if a
    c = 3
    if a > 5
        7
    else
        8
    if 9 and 10 or 2
        10

else
    111
for i, a in data
    666
    if b
        break
    else
        continue

# This is a comment
for a in data
    777
while 1
    88

a = "hi!"
b = "this is a 
multine string.. wonder how that works!"
s = 'single quoted... with \' escaping as well'