
class Coffee
    init: (flavor, size) ->
        @flavor = flavor
        @size = size
        @calories = size or 10

class Latte extends Coffee
    init: (size) ->
        super.init("Latte", size)
        @calories += size

class LowFatChaiLatte extends Latte
    init: (size) ->
        super.init(size)
        # Testing comment here
        @calories -= size
        # Testing comment on last line of init
    damn: () ->
        return 1
        # ...aaaand comment in function

new Coffee("Plain", 11).calories + 
new Latte(10).calories +
new LowFatChaiLatte(10).calories +
new LowFatChaiLatte(10).damn()
