safe: false
lsi: false
highlighter: pygments

name: bailey.js
description: bailey.js documentation
#url: http://baileyjs.io
sass:
    style: :compressed


examples:
  - Datatypes
  - Comments
  - If-statements
  - Loops
  - Classes
  - Scope
